service:
  name: feywild-days-jtg72006
frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-aws-documentation
  - serverless-offline
  - serverless-dynamodb-local
provider:
  apiGateway:
    shouldStartNameWithService: true

  tracing:
    lambda: true
    apiGateway: true
    
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region,'us-west-2'}

  environment:
    EXAMPLE_VARIABLE: sans-server-todo-jtg72006-${self:provider.stage}
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
    HARPTOS_TABLE: HarptosDB-${self:provider.stage}
    FEYWILD_TABLE: FeywildDB-${self:provider.stage}
    HARPTOS_INDEX: HarptosIndex
    FEYWILD_INDEX: FeywildIndex

  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - codedeploy:*
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Delete
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.HARPTOS_TABLE}
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Delete
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.FEYWILD_TABLE}

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: "8000"
      inMemory: true
      migrate: true
  serverless-offline:
    httpPort: 3000
  documentation:
    api:
      info:
        version: v0.1.0
        title: JTG Harptos
        description: Serverless Database for Harptos.

functions:

  Auth:
    handler: src/01Lambda/auth/auth0Authorizer.handler

  OnlineCheck:
    handler: src/01Lambda/onlineCheck.handler
    events:
      - http:
          method: get
          cors: true
          path: test
  # Harptos CRUD
  CreateHarptos:
    handler: src/01Lambda/httpHarptos/createHarptos.handler
    events:
      - http:
          method: post
          cors: true
          path: harptos/
          authorizer: Auth
  RetrieveHarptos:
    handler: src/01Lambda/httpHarptos/retrieveHarptos.handler
    events:
      - http:
          method: get
          cors: true
          path: harptos/{harptosID}
          authorizer: Auth
  UpdateHarptos:
    handler: src/01Lambda/httpHarptos/updateHarptos.handler
    events:
      - http:
          method: patch
          cors: true
          path: harptos/{harptosID}
          authorizer: Auth
  DeleteHarptos:
    handler: src/01Lambda/httpHarptos/deleteHarptos.handler
    events:
      - http:
          method: delete
          cors: true
          path: harptos/{harptosID}
          authorizer: Auth
  # Feywild CRUD
  CreateFeywild:
    handler: src/01Lambda/httpFeywild/createFeywild.handler
    events:
      - http:
          method: post
          cors: true
          path: feywild/
          authorizer: Auth
  RetrieveFeywild:
    handler: src/01Lambda/httpFeywild/getFeywild.handler
    events:
      - http:
          method: get
          cors: true
          path: feywild/{feywildID}
          authorizer: Auth
  UpdateFeywild:
    handler: src/01Lambda/httpFeywild/updateFeywild.handler
    events:
      - http:
          method: patch
          cors: true
          path: feywild/{feywildID}
          authorizer: Auth
  DeleteFeywild:
    handler: src/01Lambda/httpFeywild/deleteFeywild.handler
    events:
      - http:
          method: delete
          cors: true
          path: feywild/{feywildID}
          authorizer: Auth

resources:
  Resources:
    # TODO: Add any necessary AWS resources
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi

    # Harptos Database
    HaprtosTable:
      Type: AWS::DynamoDB::Table
      Properties:
          AttributeDefinitions:
            - AttributeName: harptosID
              AttributeType: S
            - AttributeName: userID
              AttributeType: S
          KeySchema:
            - AttributeName: harptosID
              KeyType: HASH
            - AttributeName: userID
              KeyType: RANGE
          BillingMode: PAY_PER_REQUEST
          TableName: ${self:provider.environment.HARPTOS_TABLE}
  
    # Feywild Database
    FeywildTable:
      Type: AWS::DynamoDB::Table
      Properties:
          AttributeDefinitions:
            - AttributeName: feywildID
              AttributeType: S
          KeySchema:
            - AttributeName: feywildID
              KeyType: HASH
          BillingMode: PAY_PER_REQUEST
          TableName: ${self:provider.environment.FEYWILD_TABLE}
    